//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS201724112103.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public string eqid { get; set; }
        public string eqname { get; set; }
        public string eqstandard { get; set; }
        public string eqphoto { get; set; }
        public string eqprice { get; set; }
        public string eqdate { get; set; }
        public string eqlocation { get; set; }
        public string eqmanage { get; set; }
        public string emid { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
